<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="EPBYMINW1580" name="com.epam.atm.testng.tests.CalculatorTest" tests="31" failures="3" timestamp="22 Jan 2017 10:41:08 GMT" time="26.038" errors="5">
  <testcase name="testIsNotPositive" time="0.000" classname="com.epam.atm.testng.tests.CalculatorTest">
    <error type="java.lang.Throwable" message="Method CalculatorTest.testIsNotPositive()[pri:0, instance:com.epam.atm.testng.tests.CalculatorTest@68fb2c38] depends on not successfully finished methods in group &quot;positive&quot;">
      <![CDATA[java.lang.Throwable: Method CalculatorTest.testIsNotPositive()[pri:0, instance:com.epam.atm.testng.tests.CalculatorTest@68fb2c38] depends on not successfully finished methods in group "positive"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- testIsNotPositive -->
  <testcase name="testSum" time="1.001" classname="com.epam.atm.testng.tests.CalculatorTest"/>
  <testcase name="testSum" time="1.001" classname="com.epam.atm.testng.tests.CalculatorTest"/>
  <testcase name="testDivision" time="1.002" classname="com.epam.atm.testng.tests.CalculatorTest"/>
  <testcase name="testMultiplyWithZero" time="0.999" classname="com.epam.atm.testng.tests.CalculatorTest"/>
  <testcase name="testSum" time="1.001" classname="com.epam.atm.testng.tests.CalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [3.8] but found [3.8000000000000003]">
      <![CDATA[java.lang.AssertionError: expected [3.8] but found [3.8000000000000003]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:167)
	at com.epam.atm.testng.tests.CalculatorTest.testSum(CalculatorTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- testSum -->
  <testcase name="testSum" time="1.001" classname="com.epam.atm.testng.tests.CalculatorTest"/>
  <testcase name="testIsNegative" time="1.000" classname="com.epam.atm.testng.tests.CalculatorTest"/>
  <testcase name="testSum" time="1.001" classname="com.epam.atm.testng.tests.CalculatorTest"/>
  <testcase name="testIsPositive" time="1.001" classname="com.epam.atm.testng.tests.CalculatorTest"/>
  <testcase name="testMultiply" time="1.004" classname="com.epam.atm.testng.tests.CalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [1.68] but found [1.0]">
      <![CDATA[java.lang.AssertionError: expected [1.68] but found [1.0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:167)
	at com.epam.atm.testng.tests.CalculatorTest.testMultiply(CalculatorTest.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- testMultiply -->
  <testcase name="testMultiplyByZero" time="1.009" classname="com.epam.atm.testng.tests.CalculatorTest"/>
  <testcase name="testSum" time="1.000" classname="com.epam.atm.testng.tests.CalculatorTest"/>
  <testcase name="testSum" time="1.002" classname="com.epam.atm.testng.tests.CalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [0.76] but found [0.7599999999999999]">
      <![CDATA[java.lang.AssertionError: expected [0.76] but found [0.7599999999999999]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:167)
	at com.epam.atm.testng.tests.CalculatorTest.testSum(CalculatorTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- testSum -->
  <testcase name="testZeroPOW" time="1.001" classname="com.epam.atm.testng.tests.CalculatorTest"/>
  <testcase name="testSQRT" time="1.000" classname="com.epam.atm.testng.tests.CalculatorTest"/>
  <testcase name="testDivisionByZero" time="1.011" classname="com.epam.atm.testng.tests.CalculatorTest"/>
  <testcase name="testSum" time="1.001" classname="com.epam.atm.testng.tests.CalculatorTest"/>
  <testcase name="testZeroIsNotPositive" time="0.000" classname="com.epam.atm.testng.tests.CalculatorTest">
    <error type="java.lang.Throwable" message="Method CalculatorTest.testZeroIsNotPositive()[pri:0, instance:com.epam.atm.testng.tests.CalculatorTest@68fb2c38] depends on not successfully finished methods in group &quot;positive&quot;">
      <![CDATA[java.lang.Throwable: Method CalculatorTest.testZeroIsNotPositive()[pri:0, instance:com.epam.atm.testng.tests.CalculatorTest@68fb2c38] depends on not successfully finished methods in group "positive"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- testZeroIsNotPositive -->
  <testcase name="testIsNotNegative" time="0.000" classname="com.epam.atm.testng.tests.CalculatorTest">
    <error type="java.lang.Throwable" message="Method CalculatorTest.testIsNotNegative()[pri:0, instance:com.epam.atm.testng.tests.CalculatorTest@68fb2c38] depends on not successfully finished methods in group &quot;positive&quot;">
      <![CDATA[java.lang.Throwable: Method CalculatorTest.testIsNotNegative()[pri:0, instance:com.epam.atm.testng.tests.CalculatorTest@68fb2c38] depends on not successfully finished methods in group "positive"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- testIsNotNegative -->
  <testcase name="testPOW" time="1.000" classname="com.epam.atm.testng.tests.CalculatorTest"/>
  <testcase name="testSubtractionWithZero" time="1.000" classname="com.epam.atm.testng.tests.CalculatorTest"/>
  <testcase name="testSum" time="1.000" classname="com.epam.atm.testng.tests.CalculatorTest"/>
  <testcase name="testSQRTZero" time="1.001" classname="com.epam.atm.testng.tests.CalculatorTest"/>
  <testcase name="testZeroValuePOW" time="1.000" classname="com.epam.atm.testng.tests.CalculatorTest"/>
  <testcase name="testDivisionWithZero" time="1.000" classname="com.epam.atm.testng.tests.CalculatorTest"/>
  <testcase name="testBothZeroPOW" time="0.000" classname="com.epam.atm.testng.tests.CalculatorTest">
    <error type="java.lang.Throwable" message="Method CalculatorTest.testBothZeroPOW()[pri:0, instance:com.epam.atm.testng.tests.CalculatorTest@68fb2c38] depends on not successfully finished methods in group &quot;positive&quot;">
      <![CDATA[java.lang.Throwable: Method CalculatorTest.testBothZeroPOW()[pri:0, instance:com.epam.atm.testng.tests.CalculatorTest@68fb2c38] depends on not successfully finished methods in group "positive"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- testBothZeroPOW -->
  <testcase name="testSumWithZero" time="1.001" classname="com.epam.atm.testng.tests.CalculatorTest"/>
  <testcase name="testZeroIsNotNegative" time="0.000" classname="com.epam.atm.testng.tests.CalculatorTest">
    <error type="java.lang.Throwable" message="Method CalculatorTest.testZeroIsNotNegative()[pri:0, instance:com.epam.atm.testng.tests.CalculatorTest@68fb2c38] depends on not successfully finished methods in group &quot;positive&quot;">
      <![CDATA[java.lang.Throwable: Method CalculatorTest.testZeroIsNotNegative()[pri:0, instance:com.epam.atm.testng.tests.CalculatorTest@68fb2c38] depends on not successfully finished methods in group "positive"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- testZeroIsNotNegative -->
  <testcase name="testSubtraction" time="1.001" classname="com.epam.atm.testng.tests.CalculatorTest"/>
  <testcase name="testSum" time="1.000" classname="com.epam.atm.testng.tests.CalculatorTest"/>
</testsuite> <!-- com.epam.atm.testng.tests.CalculatorTest -->
